#: import view Test
#: import model model_w_recipe
#: import controller recipes_controller
#: import ListAdapter kivy.adapters.listadapter.ListAdapter
#: import ListItemButton kivy.uix.listview.ListItemButton


# RecycleView stuff


<MyScreenManager>
    HomeScreen:
        name: "home"
    RecipeViewScreen:
        name: "recipeView"


#<RecycleViewRow>:
#    orientation: 'horizontal'
#    Button:
#        text: root.text
#        on_press: root.go_to_rec(root.text)


#<CategoryTagLabel@Label>
#    size_hint: None, None
#    size: self.texture_size
#    pos_hint: {"top": 1}


<RV>:
    viewclass: 'SelectableLabel'
    SelectableRecycleBoxLayout:
        default_size: None, dp(56)
        #This can be used to center the text in the available space
        #default_size_hint: 1, None
        size_hint_y: None
        height: self.minimum_height
        orientation: 'vertical'


<SelectableLabel>:
    # Draw a background to indicate selection
    canvas.before:
        Color:
            rgba: (.0, 0.9, .1, .3) if self.selected else (0, 0, 0, 1)
        Rectangle:
            pos: self.pos
            size: self.size


<HomeScreen>
    BoxLayout:
        padding: 10

        FloatLayout:
            size_hint: None, None
            size: 1000, 500
            pos_hint: {"x": 0, "top": 1}

            Button:
                text: "<"
                font_size: "25sp"
                size_hint: None, None
                size: 40, 40
                pos_hint: { "x": 0, "top": 1}
                on_press: root.manager.current = root.manager.previous()

            Button:
                text: ">"
                font_size: "25sp"
                size_hint: None, None
                size: 40, 40
                pos_hint: { "x": .04, "top": 1}
                on_press: root.manager.current = root.manager.previous()

            Button:
                text: "New Recipe"
                size_hint: None, None
                size: 100, 40
                pos_hint: { "x": .09, "top": 1}
                on_press: root.manager.current = 'recipeView'

            TextInput:
                hint_text: "Search"
                multiline: "false"
                size_hint: None, None
                size: 450, 30
                pos_hint: {"x": .2, "top": .99}

            Button:
                text: "Search"
                size_hint: None, None
                size: 90, 40
                pos_hint: {"x": .655, "top": 1}
                on_press: root.fill_recipe_page("Tiramisu")


            BoxLayout:
                orientation: "vertical"
                size_hint: None, None
                size: 189, 400
                pos_hint: {"x": 0, "top": .9}

                canvas:
                    Color:
                        rgba: 150/255, 150/255, 150/255, 1
                    Rectangle:
                        pos: self.pos
                        size: self.size

            Label:
                text: "All Recipes"
                font_size: 34
                size_hint: None, None
                size: self.texture_size
                pos_hint: {"x": .23, "top": .89}

            RV:
                pos_hint: {"x": .25, "top": .78}


<RecipeViewScreen>
    BoxLayout:
        padding: 10

        ScrollView:
            id: recipe_screen_scrlv
            do_scroll_x: False
            size: self.size

            FloatLayout:
                size_hint: None, None
                size: 1000, 500
                pos_hint: {"x": 0, "top": 1}

                Button:
                    text: "<"
                    font_size: 25
                    size_hint: None, None
                    size: 40, 40
                    pos_hint: { "x": 0, "top": 1}
                    on_press: root.manager.current = root.manager.previous()

                Button:
                    text: "Edit Recipe"
                    size_hint: None, None
                    size: 100, 40
                    pos_hint: { "x": .047, "top": 1}
                    on_press: root.manager.current = 'recipeView'

                Label:
                    text: "Recipe Name"
                    font_size: 33
                    size_hint: None, None
                    size: self.texture_size
                    pos_hint: {"x": .16, "top": 1}

                Button:
                    text: "Recipe Picture"
                    size_hint: None, None
                    size: 125, 125
                    pos_hint: { "x": .01, "top": .89}

                BoxLayout:
                    pos_hint: {"x": .16, "top": .89}
                    size_hint: None, None
                    size: 200, 125
                    padding: 5
                    spacing: 2
                    size_hint_x: .5
                    canvas:
                        Color:
                            rgba: 150/255, 150/255, 150/255, 1
                        Rectangle:
                            pos: self.pos
                            size: self.size

                    Label:
                        text: "Category:\nMeal:\nPrep Time:\nDifficulty:\nPrice:\nEthnicity: "
                        pos_hint: {"top": 1}
                        size_hint: None, None
                        size: self.texture_size

                Label:
                    text: "[b]Ingredients[/b]"
                    markup: True
                    font_size: 21
                    size_hint: None, None
                    size: self.texture_size
                    pos_hint: {"x": .03, "top": .6}

                Label:
                    text: "Beans\nGreeens\nTomatoes\nPotatoes\nwheat\nmilk\na\nb\nc\nd\ne\nf\ng\nh\ni\nj\nk\nl\nm\nn\no\np"
                    size_hint: None, None
                    size: self.texture_size
                    pos_hint: {"x": .03, "top": .52}

                Label:
                    text: "[b]Instructions[/b]"
                    markup: True
                    font_size: 21
                    size_hint: None, None
                    size: self.texture_size
                    pos_hint: {"x": .3, "top": .6}

                Label:
                    text: "1) Boil Water\n2) Let it cool"
                    size_hint: None, None
                    size: self.texture_size
                    pos_hint: {"x": .3, "top": .52}
